version: "3.9"

services:
  db:
    build: 
      context: db/
      args:
        MYSQL_PROD_HOST: ${MYSQL_PROD_HOST}
        MYSQL_PROD_USER: ${MYSQL_PROD_USER}
        MYSQL_PROD_PASSWORD: ${MYSQL_PROD_PASSWORD}
        MYSQL_PROD_DATABASE: ${MYSQL_PROD_DATABASE}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysql -uroot -proot -e 'show databases;'
      interval: 5s
      timeout: 2s
      retries: 10
    stop_signal: SIGKILL
  webui:
    build: webui/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9630:8000"
    volumes:
      - ./webui:/app
    environment:
      APP_ENV: development
    stop_signal: SIGKILL
  ghbot:
    build:
      context: ghbot/
      args:
        GHBOT_SMEE: ${GHBOT_SMEE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7410:2000"
    volumes:
      - ./ghbot:/app
    environment:
      APP_ENV: development
    stop_signal: SIGKILL
  crud:
    build: 
      context: crud/
      args:
        CRUD_SLACK_SMEE: ${CRUD_SLACK_SMEE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8520:2000"
    volumes:
      - ./crud:/app
    environment:
      APP_ENV: development
    stop_signal: SIGKILL